"""Report generator — Markdown, JSON, and website-ready output."""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from gnosis.data.models import (
    Run, Convergence, Finding, ConfidenceCategory, StrengthCategory,
)


def generate_markdown(run: Run) -> str:
    """Generate a full Markdown discovery report."""
    stats = run.get_stats()
    convergences = run.get_convergences()
    findings = run.get_findings()

    lines = []
    lines.append("# Gnosis AI — Discovery Report")
    lines.append("=" * 55)
    lines.append(f"**Run:** {run.id}")
    lines.append(f"**Mode:** {run.mode} | **Duration:** {run.duration_human} | **Cost:** ${stats.estimated_cost_usd:.2f}")
    if run.input_question:
        lines.append(f"**Question:** {run.input_question}")
    lines.append(f"**Domains:** {len(run.input_domains)} fields")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Domains surveyed | {stats.domains_surveyed} |")
    lines.append(f"| Results catalogued | {stats.results_catalogued} |")
    lines.append(f"| Combinations explored | {stats.combinations_explored} |")
    lines.append(f"| Convergences found | {stats.convergences_found} |")
    lines.append(f"| High-strength (≥0.75) | {stats.high_strength} |")
    lines.append(f"| Medium (0.40–0.74) | {stats.medium_strength} |")
    lines.append(f"| Meta-convergences | {stats.meta_convergences} |")
    lines.append(f"| API calls | {stats.api_calls} |")
    lines.append(f"| Tokens used | {stats.tokens_used:,} |")
    if stats.termination_reason:
        lines.append(f"| Terminated | {stats.termination_reason} |")
    lines.append("")

    # Convergences sorted by confidence
    if convergences:
        convergences.sort(key=lambda c: c.get_ea().confidence, reverse=True)

        # High strength
        high = [c for c in convergences if c.get_ea().strength >= 0.75]
        if high:
            lines.append("## High-Strength Discoveries")
            lines.append("")
            for i, c in enumerate(high, 1):
                lines.extend(_format_convergence(i, c))

        # Medium strength
        medium = [c for c in convergences if 0.4 <= c.get_ea().strength < 0.75]
        if medium:
            lines.append("## Medium-Strength Discoveries")
            lines.append("")
            for i, c in enumerate(medium, 1):
                lines.extend(_format_convergence(i, c))

        # Analogical / lower
        rest = [c for c in convergences if c.get_ea().strength < 0.4]
        if rest:
            lines.append("## Preliminary Discoveries")
            lines.append("")
            for i, c in enumerate(rest, 1):
                lines.extend(_format_convergence(i, c))

    # Meta-convergence findings
    if findings:
        lines.append("## Meta-Convergence Findings")
        lines.append("")
        for f in findings:
            term = f" — {f.coined_term}" if f.coined_term else ""
            lines.append(f"### Level {f.level}{term}")
            lines.append("")
            lines.append(f"{f.structural_finding}")
            lines.append("")
            if f.source_convergence_ids:
                lines.append(f"*Derived from convergences: {', '.join(f.source_convergence_ids)}*")
                lines.append("")

    # Methodology footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by Gnosis AI v1 using Convergent Descent — the methodology")
    lines.append("defined in the Infinitography research papers by Mark E. Mala.*")
    lines.append("")
    lines.append("*Gnosis AI is open source: github.com/wonderben-code/gnosis-ai*")

    return "\n".join(lines)


def _format_convergence(num: int, conv: Convergence) -> list[str]:
    """Format a single convergence for the Markdown report."""
    ea = conv.get_ea()
    cat = ConfidenceCategory.from_score(ea.confidence).value.upper()
    strength = StrengthCategory.from_score(ea.strength).value.upper()
    domains = ", ".join(conv.domain_names) if conv.domain_names else ", ".join(conv.domains)

    lines = []
    lines.append(f"### Discovery {num}")
    lines.append(f"**Confidence: {ea.confidence:.2f} | Strength: {strength} | Type: {conv.convergence_type}**")
    lines.append("")
    lines.append(f"**Structural claim:** {conv.structural_claim}")
    lines.append("")
    lines.append(f"**Fields:** {domains}")
    lines.append("")

    supporting = conv.get_supporting()
    if supporting:
        lines.append("**Supporting evidence:**")
        for s in supporting:
            link = "direct" if s.link_type == "direct" else "analogical"
            lines.append(f"- **{s.domain_name}:** {s.result_name} [{link}] — {s.structural_conclusion}")
        lines.append("")

    lines.append(f"**EA Validation:** Independence: {ea.independence:.2f} | "
                 f"Adversarial: {ea.adversarial:.2f} | "
                 f"Reproducibility: {ea.reproducibility:.2f}")
    lines.append("")
    return lines


def generate_json(run: Run) -> str:
    """Export run as JSON."""
    return json.dumps(asdict(run), indent=2, default=str)


def save_report(run: Run, output_path: Path, format: str = "markdown"):
    """Save a report to a file."""
    if format == "markdown":
        content = generate_markdown(run)
    elif format == "json":
        content = generate_json(run)
    else:
        raise ValueError(f"Unknown format: {format}")

    output_path.write_text(content)
